### ISSUE TITLE
Uncaught TypeError: editor.getSelection is not a function

### ISSUE THREAD

**Issue by ryz310** [hokaccha/atom-japanese-dictionary#1]
[Enter steps to reproduce below:]
1. 選択範囲の辞書翻訳を実行しようとするとエラーになります。

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [japanese-dictionary](https://github.com/hokaccha/atom-japanese-dictionary) package, v0.2.0
### Stack Trace

Uncaught TypeError: editor.getSelection is not a function

```
At /Users/RyosukeSato/.atom/packages/japanese-dictionary/lib/japanese-dictionary.coffee:44

TypeError: editor.getSelection is not a function
    at Object.module.exports.openBySelection (/Users/RyosukeSato/.atom/packages/japanese-dictionary/lib/japanese-dictionary.coffee:44:24)
    at atom-workspace.subscriptions.add.atom.commands.add.japanese-dictionary:open-by-selection (/Users/RyosukeSato/.atom/packages/japanese-dictionary/lib/japanese-dictionary.coffee:18:52)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -4:18.8.0 core:select-left (atom-text-editor.editor.is-focused)
     -4:18.6.0 core:select-down (atom-text-editor.editor.is-focused)
  3x -4:18.4.0 core:select-right (atom-text-editor.editor.is-focused)
     -4:17.5.0 core:delete (atom-text-editor.editor.is-focused)
     -4:16.9.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -4:11.6.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused)
     -4:11.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:11.2.0 core:save (atom-text-editor.editor.is-focused)
     -3:11.4.0 settings-view:open (atom-text-editor.editor.is-focused)
     -2:50.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  2x -2:48 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:27.7.0 japanese-dictionary:open-by-input (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-monokai.theme-one-dark-ui)
  4x -0:20.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:18.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.2.0 core:close (webview.)
     -0:01.2.0 japanese-dictionary:open-by-selection (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "editor-background"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "git-plus",
      "compare-files",
      "merge-conflicts"
    ],
    "projectHome": "/Users/RyosukeSato/Documents/gino/paiza",
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-alignment, v0.12.1
atom-beautify, v0.29.7
autocomplete-ruby, v0.1.0
change-case, v0.6.0
color-picker, v2.1.1
compare-files, v0.6.2
file-icons, v1.7.11
git-diff-details, v1.3.0
japanese-dictionary, v0.2.0
language-diff, v0.4.0
language-haml, v0.24.0
linter, v1.11.4
linter-coffeescript, v1.0.0
linter-haml, v1.2.0
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
linter-sass-lint, v1.5.0
linter-scss-lint, v3.0.4
merge-conflicts, v1.4.2
monokai, v0.18.0
multi-cursor, v2.1.3
pigments, v0.26.3
regex-railroad-diagram, v0.16.0
rubocop-auto-correct, v1.2.0
ruby-block, v0.3.5
ruby-syntax-replacer, v0.5.1
smarter-delete-line, v1.1.2
sort-lines, v0.14.0
sync-settings, v0.7.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by ryz310** [comment]
#2 にて対応しています。
